apiVersion: v1
kind: Service
metadata:
  name: ecommerce-web-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ecommerce-web
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80