apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-web-deployment
  labels:
    app: ecommerce-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommerce-web
  template:
    metadata:
      labels:
        app: ecommerce-web
    spec:
      containers:
      - name: ecommerce-web-container
        image: martins984/ecommerce-web-app:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"